baseURL = "https://dehors.club/"
languageCode = "en-us"
title = "Dehors club"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  footer = '🏕'

[params.social]
  email = "bonjour@dehors.club"
  domain = "dehors.club"

[params.fathom]
  host = "logs.vadrouilles.co"
  siteID = "ABKTM"

[permalinks]
  posts = "/:slug"
  pages = "/:slug"
